version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.35
    - 14.14.37
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: ts-jest
    versions:
    - 24.3.0
    - 26.5.3
    - 26.5.4
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.3
  - dependency-name: "@types/prettier"
    versions:
    - 2.2.1
    - 2.2.2
  - dependency-name: gluegun
    versions:
    - 4.6.0
    - 4.6.1
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.168
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: tslint
    versions:
    - 6.1.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: acorn
    versions:
    - 5.7.4
  - dependency-name: tslint-config-standard
    versions:
    - 9.0.0
